name: Test and lint

on:
  push:
    paths:
      - "src/**"
    branches:
      - main
      - develop

  pull_request:
    types: [opened, synchronize]
    paths:
      - "src/**"
    branches:
      - main
      - develop

jobs:
  test-lint:
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v3

      # Setup node
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          cache: "yarn"
          cache-dependency-path: yarn.lock

      # Install deps
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # Run tests
      - name: Test
        run: yarn test

      # Install biome
      - name: Install Biome
        run: yarn add --dev @biomejs/biome

        # Run linter
      - name: Lint
        run: yarn lint
